// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxl32vm5kch30Y00-s4WvBAxJAo38s9QA',
    appId: '1:695713165147:web:591df7968d245c475b747e',
    messagingSenderId: '695713165147',
    projectId: 'bank-c9346',
    authDomain: 'bank-c9346.firebaseapp.com',
    databaseURL: 'https://bank-c9346-default-rtdb.firebaseio.com',
    storageBucket: 'bank-c9346.appspot.com',
    measurementId: 'G-HTEVBYDCHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uoe9L31BQMgpWL3ND6e11b5sgiazrEk',
    appId: '1:695713165147:android:fd810348bd8668c65b747e',
    messagingSenderId: '695713165147',
    projectId: 'bank-c9346',
    databaseURL: 'https://bank-c9346-default-rtdb.firebaseio.com',
    storageBucket: 'bank-c9346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalDzqlfvHDT4HiUfqUktIPn2mHUdOcrs',
    appId: '1:695713165147:ios:c39805a1b37e46db5b747e',
    messagingSenderId: '695713165147',
    projectId: 'bank-c9346',
    databaseURL: 'https://bank-c9346-default-rtdb.firebaseio.com',
    storageBucket: 'bank-c9346.appspot.com',
    iosClientId: '695713165147-rjclofc327pm4hpbq5t3g63m9nvp3l1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBalDzqlfvHDT4HiUfqUktIPn2mHUdOcrs',
    appId: '1:695713165147:ios:c39805a1b37e46db5b747e',
    messagingSenderId: '695713165147',
    projectId: 'bank-c9346',
    databaseURL: 'https://bank-c9346-default-rtdb.firebaseio.com',
    storageBucket: 'bank-c9346.appspot.com',
    iosClientId: '695713165147-rjclofc327pm4hpbq5t3g63m9nvp3l1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank',
  );
}
